[server]
port=8000

[database]
scheme=""
username=""
password=""
host=""
dbname=""

[baseURL]
redirection="/"
url="/api/--"
user="/api/--"
visit="/api/--"
visits="/api/--"

[url]
shortIdLength=0
freeLimit=0

[app]
pageLimit=20
secretKey="key"
jwtSecret="key"
allowedPlans=[]